default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  password:
  pool: 5
  port: <%= ENV['DEV_POSTGRES_PORT'] || 5432 %>
  username: <%= ENV['DB_USERNAME'] || 'vagrant' %>

development:
  <<: *default
  database: coderwall_development

test:
  <<: *default
  database: coderwall_test

production:
  <<: *default
  database: coderwall_production
